/*
 MIT
 MIT
 MIT
 MIT
 MIT
 MIT
 MIT
 MIT
 MIT
*/
function Math3D(){}
Math3D.rotateOnArbitrary=function(a,b){var c=Math.cos(Math.PI/180*a),d=Math.sin(Math.PI/180*a),e=Math3D.normalizeVector(b),f=new Number[4][4];f[0][0]=0;f[0][1]=-e.z();f[0][2]=e.y();f[0][3]=0;f[1][0]=e.z();f[1][1]=0;f[1][2]=-e.x();f[1][3]=0;f[2][0]=-e.y();f[2][1]=e.x();f[2][2]=0;f[2][3]=0;f[3][0]=0;f[3][1]=0;f[3][2]=0;f[3][3]=1;return Math3D.addMatrix(Matrices3D.I,MatrixMath3D.addMatrix(Math3D.scalarMultiplyMatrix(f,d)),Math3D.scalarMultiplyMatrix(Math3D.multiplyMatrixWithMatrix(f,f),1-c))};
Math3D.vectorizePoints=function(a,b){var c=Math3D.subtractPoints(a,b);c.h=0;return c};Math3D.crossProduct=function(a,b){return{x:a.y*b.z-a.z*b.y,y:a.z*b.x-a.x*b.z,z:a.x*b.y-a.y*b.x,h:0}};Math3D.dotProduct=function(a,b){return a.x*b.x+a.y*b.y+a.z*b.z+a.h*b.h};Math3D.scalarMultiply=function(a,b){return{x:a.x*b,y:a.y*b,z:a.z*b,h:a.h*b}};Math3D.magnitudeOfVector=function(a){return Math.sqrt(a.x*a.x+a.y*a.y+a.z*a.z+a.h*a.h)};Math3D.addPoints=function(a,b){return{x:a.x+b.x,y:a.y+b.y,z:a.z+b.z,h:a.h+b.h}};
Math3D.addVectors=function(a,b){return Math3D.addPoints(a,b)};Math3D.subtractPoints=function(a,b){return{x:a.x-b.x,y:a.y-b.y,z:a.z-b.z,h:1}};Math3D.normalizeVector=function(a){var b={},b=Math3D.magnitudeOfVector(a);return b=Math3D.scalarMultiply(a,1/b)};Math3D.initMatrix=function(a,b){var c=[];if(a&&b)for(var d=0;d<a;d++){for(var e=[],f=0;f<b;f++)e.push(0);c.push(e)}else for(d=0;4>d;d++)c.push([0,0,0,0]);return c};
Math3D.addMatrix=function(a,b){for(var c=this.initMatrix(),d=0;4>d;d++)for(var e=0;4>e;e++)c[d][e]=a[d][e]+b[d][e];return c};Math3D.scalarMultiplyMatrix=function(a,b){for(var c=this.initMatrix(),d=0;4>d;d++)for(var e=0;4>e;e++)c[d][e]=a[d][e]*b;return c};Math3D.multiplyMatrices=function(a,b){for(var c=this.initMatrix(),d=0;4>d;d++)for(var e=0;4>e;e++){for(var f=0,g=0;4>g;g++)f+=a[d][g]*b[g][e];c[d][e]=f}return c};
Math3D.multiplyVectorByMatrix=function(a,b){return{x:b.x*a[0][0]+b.y*a[0][1]+b.z*a[0][2]+b.h*a[0][3],y:b.x*a[1][0]+b.y*a[1][1]+b.z*a[1][2]+b.h*a[1][3],z:b.x*a[2][0]+b.y*a[2][1]+b.z*a[2][2]+b.h*a[2][3],h:b.x*a[3][0]+b.y*a[3][1]+b.z*a[3][2]+b.h*a[3][3]}};Math3D.matrixCofactor=function(a,b,c){for(var d=this.initMatrix(a.length-1,a.length-1),e=0,f=0,g=0;g<d.length&&e<a.length;g++){g==b&&(e=g+1);for(var l=0;l<d.length&&f<a.length;l++)l==c&&(f=l+1),d[g][l]=a[e][f],f++;f=0;e++}return d};
Math3D.matrixDeterminate=function(a){if(2==a.length)return a[0][0]*a[1][1]-a[0][1]*a[1][0];for(var b=0,c=0;c<a.length;c++)var d=Math.floor(Math.pow(-1,c)),b=b+d*a[0][c]*this.matrixDeterminate(this.matrixCofactor(a,0,c));return b};Math3D.matrixPTranspose=function(a){for(var b=this.initMatrix(a[0].length,a.length),c=0;c<a.length;c++)for(var d=0;d<a[0].length;d++)b[d][c]=a[c][d];return b};
Math3D.matrixAdjugate=function(a){if(3>a.length)return null;for(var b=this.initMatrix(a.length,a.length),c=0;c<a.length;c++)for(var d=0;d<a.length;d++){var e=Math.floor(Math.pow(-1,c+d));b[c][d]=e*this.matrixDeterminate(this.matrixCofactor(a,c,d))}return this.matrixPTranspose(b)};Math3D.matrixInverse=function(a){var b=this.matrixDeterminate(a);a=this.matrixAdjugate(a);return this.scalarMultiplyMatrix(a,1/b)};
Matrices3D={I:[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],testA:[[2,3,1,5],[1,0,3,1],[0,2,-3,2],[0,2,3,1]],testAV:[[18,-35,-28,1],[9,-18,-14,1],[-2,4,3,0],[-12,24,19,-1]]};function matrixInversionTest(){var a=Matrices3D.testA;console.log(matrixToString(a));for(var a=Math3D.matrixInverse(a),b=!0,c=0;4>c;c++)for(var d=0;4>d;d++)a[c][d]!=Matrices3D.testAV[c][d]&&(b=!1);console.log(b,"\n",matrixToString(a))}
function matrixToString(a){for(var b="",c=0;c<a.length;c++){for(var d=0;d<a[0].length;d++)b+=a[c][d]+" ";b+="\n"}return b}"use strict";
function Canvas2D(){this.canvas=document.createElement("canvas");this.canvas.style.border="1px solid black";this.canvas.style.margin="5%";this.canvas.style.width="90%";this.canvas.style.height="90%";this.context=this.canvas.getContext("2d");document.body.appendChild(this.canvas);this.rect=this.canvas.getBoundingClientRect();$(window).on("resize",function(a){this.rect=this.canvas.getBoundingClientRect();this.canvas.width=this.rect.width;this.canvas.height=this.rect.height}.bind(this));this.canvas.width=
this.rect.width;this.canvas.height=this.rect.height;this.width=this.rect.width;this.height=this.rect.height;this.pixelImageData=this.context.createImageData(1,1)}Canvas2D.prototype.drawPixel=function(a){this.pixelImageData.data[0]=a.r;this.pixelImageData.data[1]=a.g;this.pixelImageData.data[2]=a.b;this.pixelImageData.data[3]=a.a;this.context.putImageData(this.pixelImageData,a.x,a.y)};
Canvas2D.prototype.drawLine=function(a){this.context.beginPath();this.context.moveTo(a.x1,a.y1);this.context.lineTo(a.x2,a.y2);this.context.stroke()};"use strict";
function Camera(a){this.e={x:0,y:0,z:0,h:1};this.u={};this.v={};this.n={};this.N=.5;this.F=100;this.M={};this.S1T1Mp={};this.WS2T2={};this.world={};this.e=a.position;this.g=a.gaze;this.x=this.width=a.width;this.y=this.height=a.height;this.aspect=this.width/this.height;this.theta=a.viewingAngle;this.world=a.world;var b=Math3D.vectorizePoints(this.g,this.e),c=1/Math3D.magnitudeOfVector(b);this.n=Math3D.scalarMultiply(b,c);this.u=Math3D.crossProduct({x:0,y:1,z:0,h:0},this.n);this.u=Math3D.scalarMultiply(this.u,
-1);this.v=Math3D.crossProduct(this.n,this.u);console.log(this.u,this.v,this.n);this.t=this.N*Math.tan(Math.PI/180*(this.theta/2));this.b=-this.t;this.r=this.aspect*this.t;this.l=-this.r;this.updateMatrixPipe();this.debug=!0;a.noPipe&&(this.noPipe=!0)}Camera.prototype.moveU=function(a){a=Math3D.scalarMultiply(this.u,a);this.e=Math3D.addPoints(a,this.e);this.updateMatrixPipe()};Camera.prototype.moveV=function(a){a=Math3D.scalarMultiply(this.v,a);this.e=Math3D.addPoints(a,this.e);this.updateMatrixPipe()};
Camera.prototype.moveN=function(a){a=Math3D.scalarMultiply(this.n,a);this.e=Math3D.addPoints(a,this.e);this.updateMatrixPipe()};Camera.prototype.rotateU=function(a){a=Math3D.rotateOnArbitrary(a,this.u);this.v=multiplyMatrixWithVector(a,this.v);this.n=multiplyMatrixWithVector(a,this.n)};Camera.prototype.rotateV=function(a){a=Math3D.rotateOnArbitrary(a,this.v);this.u=multiplyMatrixWithVector(a,this.u);this.n=multiplyMatrixWithVector(a,this.n)};
Camera.prototype.rotateN=function(a){a=Math3D.rotateOnArbitrary(a,this.n);this.u=multiplyMatrixWithVector(a,this.u);this.v=multiplyMatrixWithVector(a,this.v)};
Camera.prototype.updateMatrixPipe=function(){if(!this.noPipe){this.WS2T2=this.computeWS2T2();this.debug&&console.log(matrixToString(this.WS2T2));this.S1T1Mp=this.computeS1T1Mp();this.debug&&console.log(matrixToString(this.S1T1Mp));this.Mv=this.computeMv();this.debug&&console.log(matrixToString(this.Mv));var a=Math3D.multiplyMatrices(this.WS2T2,this.S1T1Mp);this.debug&&console.log(matrixToString(a));this.matrixPipe=Math3D.multiplyMatrices(a,this.Mv);this.debug&&console.log(matrixToString(this.matrixPipe))}};
Camera.prototype.computeWS2T2=function(){var a=Math3D.initMatrix(),b=this.width,c=this.height;a[0][0]=b/2;a[0][1]=0;a[0][2]=0;a[0][3]=b/2;a[1][0]=0;a[1][1]=-c/2;a[1][2]=0;a[1][3]=-c/2+c;a[2][0]=0;a[2][1]=0;a[2][2]=1;a[2][3]=0;a[3][0]=0;a[3][1]=0;a[3][2]=0;a[3][3]=1;return a};
Camera.prototype.computeS1T1Mp=function(){var a=Math3D.initMatrix(),b=this.t,c=this.b,d=this.r,e=this.l,f=this.N,g=this.F;a[0][0]=2*f/(d-1);a[0][1]=0;a[0][2]=(d+e)/(d-e);a[0][3]=0;a[1][0]=0;a[1][1]=2*f/(b-c);a[1][2]=(b+c)/(b-c);a[1][3]=0;a[2][0]=0;a[2][1]=0;a[2][2]=-(g+f)/(g-f);a[2][3]=-2*g*f/(g-f);a[3][0]=0;a[3][1]=0;a[3][2]=-1;a[3][3]=0;return a};
Camera.prototype.computeMv=function(){var a=Math3D.initMatrix(),b=this.u,c=this.v,d=this.n,e=this.e;a[0][0]=b.x;a[0][1]=b.y;a[0][2]=b.z;a[0][3]=-Math3D.dotProduct(e,b);a[1][0]=c.x;a[1][1]=c.y;a[1][2]=c.z;a[1][3]=-Math3D.dotProduct(e,c);a[2][0]=d.x;a[2][1]=d.y;a[2][2]=d.z;a[2][3]=-Math3D.dotProduct(e,d);a[3][0]=0;a[3][1]=0;a[3][2]=0;a[3][3]=1;return a};"use strict";
function GenericObject(a){if(a)for(var b in a)this[b]=a[b];this.baseC||(this.baseC={r:100,g:100,b:100,a:255});this.ambientC||(this.ambientC=this.baseC);this.diffuseC||(this.diffuseC=this.baseC);this.specularC||(this.specularC=this.baseC);this.ambientFactor||(this.ambientFactor=.1);this.diffuseFactor||(this.diffuseFactor=.75);this.specularFactor||(this.specularFactor=1);this.reflectionFactor||(this.reflectionFactor=.1);this.refractionFactor||(this.refractionFactor=0);this.specularFalloff||(this.specularFalloff=
50);this.refractionIndex||(this.refractionIndex=1.4);this.opacity||(this.opacity=1);this.transformInverse=this.transform?Math3D.matrixInverse(this.transform):this.transform=Matrices3D.I;this.UVMap||(this.UVMap=null)}GenericObject.prototype.setTransform=function(a){this.transform=a;this.transformInverse=Math3D.matrixInverse(this.transform)};GenericObject.prototype.rayIntersect=function(a){};GenericObject.prototype.getNormalAt=function(a){};GenericObject.prototype.getUVMapAt=function(a){};"use strict";
function _classCallCheck(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function");}var Light=function Light(b){_classCallCheck(this,Light);this.color=b.color?b.color:{r:255,g:255,b:255,a:255};b.intensity?this.intensity=b.intensity:this.inensity=1};"use strict";
function Ray(a){if(a.camera){this.x=a.x;this.y=a.y;this.camera=a.camera;this.superSampleRate=a.superSampleRate?a.superSampleRate:1;this.e=a.camera.e;this.u=a.camera.u;this.v=a.camera.v;this.n=a.camera.n;this.N=a.camera.N;this.W=a.camera.r;this.H=a.camera.t;this.a=a=Math3D.scalarMultiply(this.n,-this.N);var b=this.W*(2*this.x/(this.camera.width*this.superSampleRate)-1);this.bcoeff=b;this.b=b=Math3D.scalarMultiply(this.u,b);var c=this.H*(2*this.y/(this.camera.height*this.superSampleRate)-1);this.ccoeff=
c;this.c=c=Math3D.scalarMultiply(this.v,c);this.d=Math3D.addVectors(Math3D.addVectors(a,b),c)}else if(a.objectPoint&&a.targetPoint)this.e=objectPoint,this.d=Math3D.vectorizePoints(objectPoint,targetPoint),this.d=Math3D.scalarMultiply(this.d,1/Math3D.magnitudeOfVector(this.d));else if(a.e&&a.d)this.e=a.e,this.d=a.d;else throw"Error not a valid Ray Constructor";this.lowestIntersectValue=0;this.lowestIntersectPoint=this.lowestIntersectObject=null;this.intersectedObjects=[];this.intersectedObject=!1}
Ray.prototype.addIntersect=function(a){if(a.t&&a.obj){var b=Math3D.scalarMultiply(this.d,a.t),b=Math3D.addPoints(this.e,b);!this.intersectedObject&&0>a.t?(this.lowestIntersectValue=a.t,this.lowestIntersectObject=a.obj,this.lowestIntersectPoint=b,this.intersectedObjects.push(a.obj),this.intersectedObject=!0):a.t<this.lowestIntersectValue&&0>a.t&&(this.lowestIntersectValue=a.t,this.lowestIntersectObject=a.obj,this.lowestIntersectPoint=b)}else throw"Not a valid addIntersect";};
Ray.prototype.rayDetect=function(a){var b=0;0!=this.d.x?b=a.x-this.e.x/this.d.x:0!=this.d.y?b=a.y-this.e.y/this.d.y:0!=this.d.z&&(b=a.z-this.e.z/thid.d.z);return b};"use strict";var _createClass=function(){function a(a,c){for(var d=0;d<c.length;d++){var e=c[d];e.enumerable=e.enumerable||!1;e.configurable=!0;"value"in e&&(e.writable=!0);Object.defineProperty(a,e.key,e)}}return function(b,c,d){c&&a(b.prototype,c);d&&a(b,d);return b}}();
function _defineProperty(a,b,c){b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c;return a}function _classCallCheck(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function");}
var Raytracer=function(){function a(b){var c=this;_classCallCheck(this,a);this.world=b.world;this.world.some(function(a){a instanceof Camera&&(c.camera=a)});if(!this.camera)throw"World Does not have a Camera!";this.pixelRenderer=b.pixelRenderer;this.backgroundColor={r:0,g:0,b:0,a:255};this.color={r:100,g:100,b:100,a:255};this.falloffFactor=10}_createClass(a,[{key:"getObjectList",value:function(){return this.world.filter(function(a){return a instanceof GenericObject})}},{key:"getLightList",value:function(){return this.world.filter(function(a){return a instanceof
Light})}},{key:"render",value:function(){var a=_defineProperty({},Symbol.iterator,regeneratorRuntime.mark(function h(){var a,b,c,d,e;return regeneratorRuntime.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:a=0;case 2:if(!(a<this.camera.y)){f.next=18;break}b=0;case 4:if(!(b<this.camera.x)){f.next=15;break}c=new Ray({x:b,y:a,camera:this.camera});e=d=this.raytrace(c);e.x=b;e.y=a;f.next=12;return e;case 12:b++;f.next=4;break;case 15:a++;f.next=2;break;case 18:case "end":return f.stop()}},h,this)})),
c=!0,d=!1,e=void 0;try{for(var f=a[Symbol.iterator](),g;!(c=(g=f.next()).done);c=!0)this.pixelRenderer.drawPixel(g.value)}catch(l){d=!0,e=l}finally{try{if(!c&&f["return"])f["return"]()}finally{if(d)throw e;}}}},{key:"raytrace",value:function(a){var c=this.getObjectList();this.getLightList();c.map(function(c){c.rayIntersect(a)});if(a.intersectedObject){var d=a.lowestIntersectObject,c=d.ambientFactor,e=d.diffuseFactor,f=d.specularFactor,g=d.ambientC,l={r:0,g:0,b:0,a:0},k={r:0,g:0,b:0,a:0};this.getLightList()&&
(l=this._diffuseShader(a),k=this._specularShader(a));var h=g.g*c+l.g*e+k.g*f,m=g.b*c+l.b*e+k.b*f,d=255*d.opacity;return{r:Math.min(g.r*c+l.r*e+k.r*f,255),g:Math.min(h,255),b:Math.min(m,255),a:Math.min(d,255)}}return{r:this.backgroundColor.r,g:this.backgroundColor.g,b:this.backgroundColor.b,a:this.backgroundColor.a}}},{key:"_diffuseShader",value:function(a){var c=a.lowestIntersectObject,d=a.lowestIntersectPoint,e=c.getNormalAt(d),f=this.falloffFactor,g=0;this.getLightList()&&this.getLightList().map(function(c,
k,h){h=Math3D.vectorizePoints(d,c.source);Math3D.vectorizePoints(d,a.e);var m=Math3D.dotProduct(e,h);k=Math3D.magnitudeOfVector(h);-1<k&&1>k&&(k=1);h=m/(Math3D.magnitudeOfVector(h)*Math3D.magnitudeOfVector(e));c=c.intensity*Math.max(h,0)/(k/f^2);g+=c});return{r:c.diffuseC.r*g,g:c.diffuseC.g*g,b:c.diffuseC.b*g,a:255}}},{key:"_specularShader",value:function(a){var c=a.lowestIntersectObject,d=a.lowestIntersectPoint,e=c.getNormalAt(d),f=this.falloffFactor,g=0;this.getLightList()&&this.getLightList().map(function(l,
k,h){h=Math3D.vectorizePoints(d,l.source);k=Math3D.vectorizePoints(d,a.e);var m=Math3D.dotProduct(e,h),n=Math3D.magnitudeOfVector(e),m=m/(n*n)*2,n=Math3D.addVectors(Math3D.scalarMultiply(h,-1),Math3D.scalarMultiply(e,m)),m=c.specularFalloff;h=Math3D.magnitudeOfVector(h);-1<h&&1>h&&(h=1);var p=0;k=Math3D.dotProduct(k,n)/(Math3D.magnitudeOfVector(k)*Math3D.magnitudeOfVector(n));0<k&&(p=l.intensity*Math.max(Math.pow(k,m),0)/(h/f/50^2));g+=p});return{r:c.specularC.r*g,g:c.specularC.g*g,b:c.specularC.b*
g,a:255}}}]);return a}();"use strict";var _get=function(a,b,c){var d=!0;for(;d;)if(null===a&&(a=Function.prototype),d=Object.getOwnPropertyDescriptor(a,b),void 0===d){a=Object.getPrototypeOf(a);if(null===a)break;d=!0}else{if("value"in d)return d.value;b=d.get;return void 0===b?void 0:b.call(c)}};function _classCallCheck(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function");}
function _inherits(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(a,b):a.__proto__=b)}
var OmniLight=function(a){function b(a){_classCallCheck(this,b);_get(Object.getPrototypeOf(b.prototype),"constructor",this).call(this,a);if(a.source)this.source=a.source;else throw"Please define source in config for OmniLight";}_inherits(b,a);return b}(Light);"use strict";"use strict";function Sphere(a){GenericObject.call(this,a)}Sphere.prototype=Object.create(GenericObject.prototype);Sphere.constructor=Sphere;
Sphere.prototype.rayIntersect=function(a){var b=a.d,c=Math3D.multiplyVectorByMatrix(this.transformInverse,a.e),d=Math3D.multiplyVectorByMatrix(this.transformInverse,b),e={x:c.x,y:c.y,z:c.z,h:0},b=Math3D.magnitudeOfVector(d),e=Math3D.magnitudeOfVector(e),b=b*b,c=Math3D.dotProduct(c,d),e=c*c-b*(e*e-1);0==e&&a.addIntersect(c/b,this);0<e&&(d=-c/b+Math.sqrt(e)/b,c=-c/b-Math.sqrt(e)/b,a.addIntersect({t:d,obj:this}),a.addIntersect({t:c,obj:this}))};
Sphere.prototype.getNormalAt=function(a){a=Math3D.multiplyVectorByMatrix(this.transformInverse,a);a={x:a.x,y:a.y,z:a.z,h:0};a=Math3D.normalizeVector(a);return a=Math3D.multiplyVectorByMatrix(this.transform,a)};Sphere.prototype.getUVMapAt=function(a){return{r:0,g:0,b:0,a:0}};"use strict";
(function(){window.canvas2D=new Canvas2D;var a=new Camera({position:{x:0,y:16,z:2.5,h:1},gaze:{x:0,y:0,z:0,h:1},width:canvas2D.width,height:canvas2D.height,viewingAngle:90,world:null,noPipe:!1}),b=new Sphere({baseC:{r:0,g:0,b:255,a:255},specularC:{r:255,g:255,b:255,a:255}}),c=new OmniLight({intensity:1.8,source:{x:-8,y:12,z:1,h:1}}),d=[];d.push(a);d.push(b);d.push(c);console.log(d);var e=new Raytracer({world:d,pixelRenderer:window.canvas2D});console.log(e);e.render();$(window).on("resize",function(){e.render()})})();
