/*
 MIT
 MIT
 MIT
 MIT
 MIT
 MIT
 MIT
 MIT
 MIT
 MIT
*/
function Math3D(){}
Math3D.rotateOnArbitrary=function(b,a){var e=Math.cos(Math.PI/180*b),c=Math.sin(Math.PI/180*b),d=Math3D.normalizeVector(a),f=new Number[4][4];f[0][0]=0;f[0][1]=-d.z();f[0][2]=d.y();f[0][3]=0;f[1][0]=d.z();f[1][1]=0;f[1][2]=-d.x();f[1][3]=0;f[2][0]=-d.y();f[2][1]=d.x();f[2][2]=0;f[2][3]=0;f[3][0]=0;f[3][1]=0;f[3][2]=0;f[3][3]=1;return Math3D.addMatrix(Matrices3D.I,MatrixMath3D.addMatrix(Math3D.scalarMultiplyMatrix(f,c)),Math3D.scalarMultiplyMatrix(Math3D.multiplyMatrixWithMatrix(f,f),1-e))};
Math3D.vectorizePoints=function(b,a){var e=Math3D.subtractPoints(b,a);e.h=0;return e};Math3D.crossProduct=function(b,a){return{x:b.y*a.z-b.z*a.y,y:b.z*a.x-b.x*a.z,z:b.x*a.y-b.y*a.x,h:0}};Math3D.dotProduct=function(b,a){return b.x*a.x+b.y*a.y+b.z*a.z+b.h*a.h};Math3D.scalarMultiply=function(b,a){return{x:b.x*a,y:b.y*a,z:b.z*a,h:b.h*a}};Math3D.magnitudeOfVector=function(b){return Math.sqrt(b.x*b.x+b.y*b.y+b.z*b.z+b.h*b.h)};Math3D.addPoints=function(b,a){return{x:b.x+a.x,y:b.y+a.y,z:b.z+a.z,h:b.h+a.h}};
Math3D.addVectors=function(b,a){return Math3D.addPoints(b,a)};Math3D.subtractPoints=function(b,a){return{x:b.x-a.x,y:b.y-a.y,z:b.z-a.z,h:1}};Math3D.normalizeVector=function(b){var a={},a=Math3D.magnitudeOfVector(b);return a=Math3D.scalarMultiply(b,1/a)};Math3D.initMatrix=function(b,a){var e=[];if(b&&a)for(var c=0;c<b;c++){for(var d=[],f=0;f<a;f++)d.push(0);e.push(d)}else for(c=0;4>c;c++)e.push([0,0,0,0]);return e};
Math3D.addMatrix=function(b,a){for(var e=this.initMatrix(),c=0;4>c;c++)for(var d=0;4>d;d++)e[c][d]=b[c][d]+a[c][d];return e};Math3D.scalarMultiplyMatrix=function(b,a){for(var e=this.initMatrix(),c=0;4>c;c++)for(var d=0;4>d;d++)e[c][d]=b[c][d]*a;return e};Math3D.multiplyMatrices=function(b,a){for(var e=this.initMatrix(),c=0;4>c;c++)for(var d=0;4>d;d++){for(var f=0,g=0;4>g;g++)f+=b[c][g]*a[g][d];e[c][d]=f}return e};
Math3D.multiplyVectorByMatrix=function(b,a){return{x:a.x*b[0][0]+a.y*b[0][1]+a.z*b[0][2]+a.h*b[0][3],y:a.x*b[1][0]+a.y*b[1][1]+a.z*b[1][2]+a.h*b[1][3],z:a.x*b[2][0]+a.y*b[2][1]+a.z*b[2][2]+a.h*b[2][3],h:a.x*b[3][0]+a.y*b[3][1]+a.z*b[3][2]+a.h*b[3][3]}};Math3D.matrixCofactor=function(b,a,e){for(var c=this.initMatrix(b.length-1,b.length-1),d=0,f=0,g=0;g<c.length&&d<b.length;g++){g==a&&(d=g+1);for(var h=0;h<c.length&&f<b.length;h++)h==e&&(f=h+1),c[g][h]=b[d][f],f++;f=0;d++}return c};
Math3D.matrixDeterminate=function(b){if(2==b.length)return b[0][0]*b[1][1]-b[0][1]*b[1][0];for(var a=0,e=0;e<b.length;e++)var c=Math.floor(Math.pow(-1,e)),a=a+c*b[0][e]*this.matrixDeterminate(this.matrixCofactor(b,0,e));return a};Math3D.matrixPTranspose=function(b){for(var a=this.initMatrix(b[0].length,b.length),e=0;e<b.length;e++)for(var c=0;c<b[0].length;c++)a[c][e]=b[e][c];return a};
Math3D.matrixAdjugate=function(b){if(3>b.length)return null;for(var a=this.initMatrix(b.length,b.length),e=0;e<b.length;e++)for(var c=0;c<b.length;c++){var d=Math.floor(Math.pow(-1,e+c));a[e][c]=d*this.matrixDeterminate(this.matrixCofactor(b,e,c))}return this.matrixPTranspose(a)};Math3D.matrixInverse=function(b){var a=this.matrixDeterminate(b);b=this.matrixAdjugate(b);return this.scalarMultiplyMatrix(b,1/a)};
var Matrices3D={I:[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],testA:[[2,3,1,5],[1,0,3,1],[0,2,-3,2],[0,2,3,1]],testAV:[[18,-35,-28,1],[9,-18,-14,1],[-2,4,3,0],[-12,24,19,-1]]};function matrixInversionTest(){var b=Matrices3D.testA;console.log(matrixToString(b));for(var b=Math3D.matrixInverse(b),a=!0,e=0;4>e;e++)for(var c=0;4>c;c++)b[e][c]!=Matrices3D.testAV[e][c]&&(a=!1);console.log(a,"\n",matrixToString(b))}
function matrixToString(b){for(var a="",e=0;e<b.length;e++){for(var c=0;c<b[0].length;c++)a+=b[e][c]+" ";a+="\n"}return a}"use strict";var _createClass=function(){function b(a,b){for(var c=0;c<b.length;c++){var d=b[c];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,d.key,d)}}return function(a,e,c){e&&b(a.prototype,e);c&&b(a,c);return a}}();
function _classCallCheck(b,a){if(!(b instanceof a))throw new TypeError("Cannot call a class as a function");}
var Canvas2D=function(){function b(){_classCallCheck(this,b);this.container=document.createElement("div");this.canvas=document.createElement("canvas");this.canvas.style.border="1px solid black";this.canvas.style.width="100%";this.canvas.style.height="100%";this.canvas.style.position="absolute";this.container.style.margin="5%";this.container.style.width="90%";this.container.style.height=.8*window.innerHeight+"px";this.container.style.position="relative";this.context=this.canvas.getContext("2d");this.container.appendChild(this.canvas);
document.body.appendChild(this.container);this.rect=this.canvas.getBoundingClientRect();$(window).on("resize",function(a){this.rect=this.canvas.getBoundingClientRect();this.canvas.width=this.rect.width;this.canvas.height=this.rect.height;this.width=this.rect.width;this.height=this.rect.height;this.buffer=this.context.createImageData(this.width,this.height)}.bind(this));this.canvas.width=this.rect.width;this.canvas.height=this.rect.height;this.width=this.rect.width;this.height=this.rect.height;this.pixelImageData=
this.context.createImageData(1,1);this.buffer=this.context.createImageData(this.width,this.height)}_createClass(b,[{key:"drawPixel",value:function(a){this.pixelImageData.data[0]=a.r;this.pixelImageData.data[1]=a.g;this.pixelImageData.data[2]=a.b;this.pixelImageData.data[3]=a.a;this.context.putImageData(this.pixelImageData,a.x,a.y)}},{key:"drawPixelToBuffer",value:function(a){var b=4*(a.x+a.y*this.width)-4;this.buffer.data[b]=a.r;this.buffer.data[b+1]=a.g;this.buffer.data[b+2]=a.b;this.buffer.data[b+
3]=a.a}},{key:"flushBuffer",value:function(){this.context.putImageData(this.buffer,0,0)}},{key:"clearBuffer",value:function(){this.buffer=this.context.createImageData(this.width,this.height)}},{key:"drawLine",value:function(a){this.context.beginPath();this.context.moveTo(a.x1,a.y1);this.context.lineTo(a.x2,a.y2);this.context.stroke()}}]);return b}();"use strict";
_createClass=function(){function b(a,b){for(var c=0;c<b.length;c++){var d=b[c];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,d.key,d)}}return function(a,e,c){e&&b(a.prototype,e);c&&b(a,c);return a}}();function _classCallCheck(b,a){if(!(b instanceof a))throw new TypeError("Cannot call a class as a function");}
var Camera=function(){function b(a){_classCallCheck(this,b);this.e={x:0,y:0,z:0,h:1};this.u={};this.v={};this.n={};this.N=.5;this.F=100;this.M={};this.S1T1Mp={};this.WS2T2={};this.world={};this.e=a.position;this.g=a.gaze;this.width=a.width;this.height=a.height;this.setupVectors=function(){this.x=this.width;this.y=this.height;this.aspect=this.width/this.height;this.theta=a.viewingAngle;this.world=a.world;var b=Math3D.vectorizePoints(this.g,this.e),c=1/Math3D.magnitudeOfVector(b);this.n=Math3D.scalarMultiply(b,
c);this.u=Math3D.crossProduct({x:0,y:1,z:0,h:0},this.n);this.u=Math3D.scalarMultiply(this.u,-1);this.v=Math3D.crossProduct(this.n,this.u);this.t=this.N*Math.tan(Math.PI/180*(this.theta/2));this.b=-this.t;this.r=this.aspect*this.t;this.l=-this.r;this.updateMatrixPipe()}.bind(this);this.setupVectors();this.debug=!1;a.noPipe&&(this.noPipe=!0)}_createClass(b,[{key:"moveU",value:function(a){a=Math3D.scalarMultiply(this.u,a);this.e=Math3D.addPoints(a,this.e);this.updateMatrixPipe()}},{key:"moveV",value:function(a){a=
Math3D.scalarMultiply(this.v,a);this.e=Math3D.addPoints(a,this.e);this.updateMatrixPipe()}},{key:"moveN",value:function(a){a=Math3D.scalarMultiply(this.n,a);this.e=Math3D.addPoints(a,this.e);this.updateMatrixPipe()}},{key:"rotateU",value:function(a){a=Math3D.rotateOnArbitrary(a,this.u);this.v=multiplyMatrixWithVector(a,this.v);this.n=multiplyMatrixWithVector(a,this.n)}},{key:"rotateV",value:function(a){a=Math3D.rotateOnArbitrary(a,this.v);this.u=multiplyMatrixWithVector(a,this.u);this.n=multiplyMatrixWithVector(a,
this.n)}},{key:"rotateN",value:function(a){a=Math3D.rotateOnArbitrary(a,this.n);this.u=multiplyMatrixWithVector(a,this.u);this.v=multiplyMatrixWithVector(a,this.v)}},{key:"updateMatrixPipe",value:function(){if(!this.noPipe){this.WS2T2=this.computeWS2T2();this.debug&&console.log(matrixToString(this.WS2T2));this.S1T1Mp=this.computeS1T1Mp();this.debug&&console.log(matrixToString(this.S1T1Mp));this.Mv=this.computeMv();this.debug&&console.log(matrixToString(this.Mv));var a=Math3D.multiplyMatrices(this.WS2T2,
this.S1T1Mp);this.debug&&console.log(matrixToString(a));this.matrixPipe=Math3D.multiplyMatrices(a,this.Mv);this.debug&&console.log(matrixToString(this.matrixPipe))}}},{key:"computeWS2T2",value:function(){var a=Math3D.initMatrix(),b=this.width,c=this.height;a[0][0]=b/2;a[0][1]=0;a[0][2]=0;a[0][3]=b/2;a[1][0]=0;a[1][1]=-c/2;a[1][2]=0;a[1][3]=-c/2+c;a[2][0]=0;a[2][1]=0;a[2][2]=1;a[2][3]=0;a[3][0]=0;a[3][1]=0;a[3][2]=0;a[3][3]=1;return a}},{key:"computeS1T1Mp",value:function(){var a=Math3D.initMatrix(),
b=this.t,c=this.b,d=this.r,f=this.l,g=this.N,h=this.F;a[0][0]=2*g/(d-1);a[0][1]=0;a[0][2]=(d+f)/(d-f);a[0][3]=0;a[1][0]=0;a[1][1]=2*g/(b-c);a[1][2]=(b+c)/(b-c);a[1][3]=0;a[2][0]=0;a[2][1]=0;a[2][2]=-(h+g)/(h-g);a[2][3]=-2*h*g/(h-g);a[3][0]=0;a[3][1]=0;a[3][2]=-1;a[3][3]=0;return a}},{key:"computeMv",value:function(){var a=Math3D.initMatrix(),b=this.u,c=this.v,d=this.n,f=this.e;a[0][0]=b.x;a[0][1]=b.y;a[0][2]=b.z;a[0][3]=-Math3D.dotProduct(f,b);a[1][0]=c.x;a[1][1]=c.y;a[1][2]=c.z;a[1][3]=-Math3D.dotProduct(f,
c);a[2][0]=d.x;a[2][1]=d.y;a[2][2]=d.z;a[2][3]=-Math3D.dotProduct(f,d);a[3][0]=0;a[3][1]=0;a[3][2]=0;a[3][3]=1;return a}}]);return b}();"use strict";_createClass=function(){function b(a,b){for(var c=0;c<b.length;c++){var d=b[c];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,d.key,d)}}return function(a,e,c){e&&b(a.prototype,e);c&&b(a,c);return a}}();
function _classCallCheck(b,a){if(!(b instanceof a))throw new TypeError("Cannot call a class as a function");}
var GenericObject=function(){function b(a){_classCallCheck(this,b);if(a)for(var e in a)this[e]=a[e];this.baseC||(this.baseC={r:100,g:100,b:100,a:255});this.ambientC||(this.ambientC=this.baseC);this.diffuseC||(this.diffuseC=this.baseC);this.specularC||(this.specularC=this.baseC);this.ambientFactor||(this.ambientFactor=.1);this.diffuseFactor||(this.diffuseFactor=.75);this.specularFactor||(this.specularFactor=.9);this.reflectionFactor||(this.reflectionFactor=.4);this.refractionFactor||(this.refractionFactor=
0);this.specularFalloff||(this.specularFalloff=50);this.refractionIndex||(this.refractionIndex=1.4);this.opacity||(this.opacity=1);this.transformInverse=this.transform?Math3D.matrixInverse(this.transform):this.transform=Matrices3D.I;this.UVMap||(this.UVMap=null)}_createClass(b,[{key:"setTransform",value:function(a){this.transform=a;this.transformInverse=Math3D.matrixInverse(this.transform)}},{key:"rayIntersect",value:function(a){}},{key:"getNormalAt",value:function(a){}},{key:"getUVMapAt",value:function(a){}}]);
return b}();"use strict";function _classCallCheck(b,a){if(!(b instanceof a))throw new TypeError("Cannot call a class as a function");}var Light=function Light(a){_classCallCheck(this,Light);this.color=a.color?a.color:{r:255,g:255,b:255,a:255};a.intensity?this.intensity=a.intensity:this.inensity=1};"use strict";
_createClass=function(){function b(a,b){for(var c=0;c<b.length;c++){var d=b[c];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,d.key,d)}}return function(a,e,c){e&&b(a.prototype,e);c&&b(a,c);return a}}();function _classCallCheck(b,a){if(!(b instanceof a))throw new TypeError("Cannot call a class as a function");}
var Ray=function(){function b(a){_classCallCheck(this,b);if(a.camera){this.x=a.x;this.y=a.y;this.camera=a.camera;this.superSampleRate=a.superSampleRate?a.superSampleRate:1;this.e=a.camera.e;this.u=a.camera.u;this.v=a.camera.v;this.n=a.camera.n;this.N=a.camera.N;this.W=a.camera.r;this.H=a.camera.t;var e=Math3D.scalarMultiply(this.n,-this.N);this.a=e;var c=this.W*(2*this.x/(this.camera.width*this.superSampleRate)-1);this.bcoeff=c;this.b=c=Math3D.scalarMultiply(this.u,c);var d=this.H*(2*this.y/(this.camera.height*
this.superSampleRate)-1);this.ccoeff=d;this.c=d=Math3D.scalarMultiply(this.v,d);this.d=Math3D.addVectors(Math3D.addVectors(e,c),d)}else if(a.objectPoint&&a.targetPoint)this.e=objectPoint,this.d=Math3D.vectorizePoints(objectPoint,targetPoint),this.d=Math3D.scalarMultiply(this.d,1/Math3D.magnitudeOfVector(this.d));else if(a.e&&a.d)this.e=a.e,this.d=a.d;else throw"Error not a valid Ray Constructor";this.depth=a.depth;this.exclusionObj=a.exclusionObj?a.exclusionObj:{};this.lowestIntersectValue=0;this.lowestIntersectPoint=
this.lowestIntersectObject=null;this.intersectedObjects=[];this.intersectedObject=!1}_createClass(b,[{key:"addIntersect",value:function(a){if(a.obj!=this.exclusionObj)if(a.t&&a.obj){var b=Math3D.scalarMultiply(this.d,a.t),b=Math3D.addPoints(this.e,b);!this.intersectedObject&&0>a.t?(this.lowestIntersectValue=a.t,this.lowestIntersectObject=a.obj,this.lowestIntersectPoint=b,this.intersectedObjects.push(a.obj),this.intersectedObject=!0):a.t>this.lowestIntersectValue&&0>a.t&&(this.lowestIntersectValue=
a.t,this.lowestIntersectObject=a.obj,this.lowestIntersectPoint=b)}else throw"Not a valid addIntersect";}},{key:"rayDetect",value:function(a){var b=0;0!=this.d.x?b=a.x-this.e.x/this.d.x:0!=this.d.y?b=a.y-this.e.y/this.d.y:0!=this.d.z&&(b=a.z-this.e.z/thid.d.z);return b}}]);return b}();"use strict";
_createClass=function(){function b(a,b){for(var c=0;c<b.length;c++){var d=b[c];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,d.key,d)}}return function(a,e,c){e&&b(a.prototype,e);c&&b(a,c);return a}}();function _classCallCheck(b,a){if(!(b instanceof a))throw new TypeError("Cannot call a class as a function");}
var Raytracer=function(){function b(a){var e=this;_classCallCheck(this,b);this.world=a.world;this.world.some(function(a){a instanceof Camera&&(e.camera=a)});if(!this.camera)throw"World Does not have a Camera!";this.pixelRenderer=a.pixelRenderer;this.backgroundColor={r:0,g:0,b:0,a:255};this.color={r:100,g:100,b:100,a:255};this.falloffFactor=10;this.recursionFactor=4;this.drawTitle()}_createClass(b,[{key:"drawTitle",value:function(){var a=this.pixelRenderer.height,b=this.pixelRenderer.context,c=this.pixelRenderer.width/
2,d=2/3*a;b.font="30pt Helvetica,Arial,sans-serif";b.textAlign="center";b.fillStyle="Black";b.fillText("Raytracer-JS",c,1/3*a);b.font="15pt Helvetica,Arial,sans-serif";b.fillText("Version 0.0.1 By SparkX120",c,d)}},{key:"drawRenderingPlaceholder",value:function(){var a=this.pixelRenderer.width,b=this.pixelRenderer.height,c=this.pixelRenderer.context;c.fillStyle="rgba(255,255,255,1)";c.fillRect(0,0,a,b);this.progress=document.createElement("progress");this.progress.max=100;this.progress.value=0;this.progress.style.zindex=
"99";this.progress.style.width="100%";this.progress.style.height="3em";this.progress.style.bottom="50%";this.progress.style.position="absolute";this.progress.style.border="1px solid black";this.progress.className="prog";this.pixelRenderer.container&&this.pixelRenderer.container.appendChild(this.progress)}},{key:"getObjectList",value:function(){return this.world.filter(function(a){return a instanceof GenericObject})}},{key:"getLightList",value:function(){return this.world.filter(function(a){return a instanceof
Light})}},{key:"render",value:function(){var a=this;this.drawRenderingPlaceholder();setTimeout(function(){a.pixelRenderer.clearBuffer();a.camera.width=a.pixelRenderer.width;a.camera.height=a.pixelRenderer.height;a.camera.setupVectors();var b=0,c=setInterval(function(){if(b<a.camera.y){b++;for(var d=0;d<a.camera.x;d++){var f=new Ray({x:d,y:b,camera:a.camera,depth:0}),f=a.raytrace(f);f.x=d;f.y=b;a.pixelRenderer.drawPixel(f)}d=Math.floor(b/a.camera.y*100);a.progress&&a.progress.value!=d&&(a.progress.value=
d)}else a.progress&&(a.pixelRenderer.container.removeChild(a.progress),a.progress=null),clearTimeout(c)},1)},10)}},{key:"raytrace",value:function(a){var b=this.getObjectList();this.getLightList();b.map(function(b){b.rayIntersect(a)});if(a.intersectedObject){var c=a.lowestIntersectObject,b=c.ambientFactor,d=c.diffuseFactor,f=c.specularFactor,g=c.reflectionFactor,h=c.ambientC,l={r:0,g:0,b:0,a:0},k={r:0,g:0,b:0,a:0},m={r:0,g:0,b:0,a:0};this.getLightList()&&(0<c.diffuseFactor&&(l=this._diffuseShader(a)),
0<c.specularColor&&(k=this._specularShader(a)),0<c.reflectionFactor&&(m=this._reflectionShader(a)));var p=h.g*b+l.g*d+k.g*f+m.g*g,n=h.b*b+l.b*d+k.b*f+m.b*g,c=255*c.opacity;return{r:Math.min(h.r*b+l.r*d+k.r*f+m.r*g,255),g:Math.min(p,255),b:Math.min(n,255),a:Math.min(c,255)}}return{r:this.backgroundColor.r,g:this.backgroundColor.g,b:this.backgroundColor.b,a:this.backgroundColor.a}}},{key:"_diffuseShader",value:function(a){var b=this,c=a.lowestIntersectObject,d=a.lowestIntersectPoint,f=c.getNormalAt(d),
g=0;this.getLightList()&&this.getLightList().map(function(h,l,k){k=Math3D.vectorizePoints(d,h.source);Math3D.vectorizePoints(d,a.e);l=Math3D.dotProduct(f,k);var m=new Ray({e:d,d:k,exclusionObj:c});b.getObjectList().map(function(a){a.rayIntersect(m)});m.intersectedObject||(k=Math3D.magnitudeOfVector(k)*Math3D.magnitudeOfVector(f),0!=k&&(h=h.intensity*Math.max(l/k,0),g+=h))});return{r:c.diffuseC.r*g,g:c.diffuseC.g*g,b:c.diffuseC.b*g,a:255}}},{key:"_specularShader",value:function(a){var b=this,c=a.lowestIntersectObject,
d=a.lowestIntersectPoint,f=c.getNormalAt(d),g=0;this.getLightList()&&this.getLightList().map(function(h,l,k){k=Math3D.vectorizePoints(d,h.source);l=Math3D.vectorizePoints(d,a.e);var m=Math3D.dotProduct(f,k),p=new Ray({e:d,d:k,exclusionObj:c});b.getObjectList().map(function(a){a.rayIntersect(p)});if(!p.intersectedObject){var n=Math3D.magnitudeOfVector(f),m=m/(n*n)*2,n=Math3D.addVectors(Math3D.scalarMultiply(k,-1),Math3D.scalarMultiply(f,m));k=c.specularFalloff;m=0;l=Math3D.dotProduct(l,n)/(Math3D.magnitudeOfVector(l)*
Math3D.magnitudeOfVector(n));0<l&&(m=h.intensity*Math.max(Math.pow(l,k),0));g+=m}});return{r:c.specularC.r*g,g:c.specularC.g*g,b:c.specularC.b*g,a:255}}},{key:"_reflectionShader",value:function(a){var b=a.lowestIntersectObject,c=a.lowestIntersectPoint,d=b.getNormalAt(c),f=Math3D.dotProduct(Math3D.normalizeVector(a.d),Math3D.normalizeVector(d));return 0<b.reflectionFactor&&a.depth<this.recursionFactor&&0>f?(d=Math3D.scalarMultiply(d,-2*f),d=Math3D.normalizeVector(d),a=new Ray({e:c,d:d,depth:a.depth+
1,exclusionObj:b}),a=this.raytrace(a),{r:a.r,g:a.g,b:a.b,a:255}):this.backgroundColor}}]);return b}();"use strict";var _get=function(b,a,e){var c=!0;for(;c;)if(null===b&&(b=Function.prototype),c=Object.getOwnPropertyDescriptor(b,a),void 0===c){b=Object.getPrototypeOf(b);if(null===b)break;c=!0}else{if("value"in c)return c.value;a=c.get;return void 0===a?void 0:a.call(e)}};function _classCallCheck(b,a){if(!(b instanceof a))throw new TypeError("Cannot call a class as a function");}
function _inherits(b,a){if("function"!==typeof a&&null!==a)throw new TypeError("Super expression must either be null or a function, not "+typeof a);b.prototype=Object.create(a&&a.prototype,{constructor:{value:b,enumerable:!1,writable:!0,configurable:!0}});a&&(Object.setPrototypeOf?Object.setPrototypeOf(b,a):b.__proto__=a)}
var OmniLight=function(b){function a(b){_classCallCheck(this,a);_get(Object.getPrototypeOf(a.prototype),"constructor",this).call(this,b);if(b.source)this.source=b.source;else throw"Please define source in config for OmniLight";}_inherits(a,b);return a}(Light);"use strict";
_createClass=function(){function b(a,b){for(var c=0;c<b.length;c++){var d=b[c];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,d.key,d)}}return function(a,e,c){e&&b(a.prototype,e);c&&b(a,c);return a}}();_get=function(b,a,e){var c=!0;for(;c;)if(null===b&&(b=Function.prototype),c=Object.getOwnPropertyDescriptor(b,a),void 0===c){b=Object.getPrototypeOf(b);if(null===b)break;c=!0}else{if("value"in c)return c.value;a=c.get;return void 0===a?void 0:a.call(e)}};
function _classCallCheck(b,a){if(!(b instanceof a))throw new TypeError("Cannot call a class as a function");}function _inherits(b,a){if("function"!==typeof a&&null!==a)throw new TypeError("Super expression must either be null or a function, not "+typeof a);b.prototype=Object.create(a&&a.prototype,{constructor:{value:b,enumerable:!1,writable:!0,configurable:!0}});a&&(Object.setPrototypeOf?Object.setPrototypeOf(b,a):b.__proto__=a)}
var Plane=function(b){function a(b){_classCallCheck(this,a);_get(Object.getPrototypeOf(a.prototype),"constructor",this).call(this,b);b.restricted&&(this.restricted=b.restricted)}_inherits(a,b);_createClass(a,[{key:"rayIntersect",value:function(a){var b=a.d,d=Math3D.multiplyVectorByMatrix(this.transformInverse,a.e),f=Math3D.multiplyVectorByMatrix(this.transformInverse,b);if(0!=f.z&&(b=-(d.z/f.z),0>b))if(this.restricted){var g=d.x+f.x*b,d=d.y+f.y*b;1>=Math.sqrt(g*g+d*d)&&a.addIntersect({t:b,obj:this})}else a.addIntersect({t:b,
obj:this})}},{key:"getNormalAt",value:function(a){a={x:0,y:0,z:-1,h:1};return a=Math3D.multiplyVectorByMatrix(this.transform,a)}},{key:"getUVMapAt",value:function(a){return{r:0,g:0,b:0,a:0}}}]);return a}(GenericObject);"use strict";_createClass=function(){function b(a,b){for(var c=0;c<b.length;c++){var d=b[c];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,d.key,d)}}return function(a,e,c){e&&b(a.prototype,e);c&&b(a,c);return a}}();
_get=function(b,a,e){var c=!0;for(;c;)if(null===b&&(b=Function.prototype),c=Object.getOwnPropertyDescriptor(b,a),void 0===c){b=Object.getPrototypeOf(b);if(null===b)break;c=!0}else{if("value"in c)return c.value;a=c.get;return void 0===a?void 0:a.call(e)}};function _classCallCheck(b,a){if(!(b instanceof a))throw new TypeError("Cannot call a class as a function");}
function _inherits(b,a){if("function"!==typeof a&&null!==a)throw new TypeError("Super expression must either be null or a function, not "+typeof a);b.prototype=Object.create(a&&a.prototype,{constructor:{value:b,enumerable:!1,writable:!0,configurable:!0}});a&&(Object.setPrototypeOf?Object.setPrototypeOf(b,a):b.__proto__=a)}
var Sphere=function(b){function a(b){_classCallCheck(this,a);_get(Object.getPrototypeOf(a.prototype),"constructor",this).call(this,b)}_inherits(a,b);_createClass(a,[{key:"rayIntersect",value:function(a){var b=a.d,d=Math3D.multiplyVectorByMatrix(this.transformInverse,a.e),f=Math3D.multiplyVectorByMatrix(this.transformInverse,b),g={x:d.x,y:d.y,z:d.z,h:0},b=Math3D.magnitudeOfVector(f),g=Math3D.magnitudeOfVector(g),b=b*b,d=Math3D.dotProduct(d,f),g=d*d-b*(g*g-1);0==g&&a.addIntersect(d/b,this);0<g&&(f=
-d/b+Math.sqrt(g)/b,d=-d/b-Math.sqrt(g)/b,a.addIntersect({t:f,obj:this}),a.addIntersect({t:d,obj:this}))}},{key:"getNormalAt",value:function(a){a=Math3D.multiplyVectorByMatrix(this.transformInverse,a);a={x:-a.x,y:-a.y,z:-a.z,h:0};a=Math3D.normalizeVector(a);return a=Math3D.multiplyVectorByMatrix(this.transform,a)}},{key:"getUVMapAt",value:function(a){return{r:0,g:0,b:0,a:0}}}]);return a}(GenericObject);"use strict";
(function(){window.canvas2D=new Canvas2D;$(window).on("load",function(){var b=new Camera({position:{x:0,y:5,z:5,h:1},gaze:{x:0,y:0,z:0,h:1},width:canvas2D.width,height:canvas2D.height,viewingAngle:90,world:null,noPipe:!1}),a=new Sphere({baseC:{r:0,g:0,b:255,a:255},specularC:{r:255,g:255,b:255,a:255},transform:[[1,0,0,2],[0,1,0,0],[0,0,1,0],[0,0,0,1]]}),e=new Sphere({baseC:{r:0,g:0,b:255,a:255},specularC:{r:255,g:255,b:255,a:255},transform:[[1,0,0,0],[0,1,0,2],[0,0,1,0],[0,0,0,1]]}),c=new Sphere({baseC:{r:0,
g:0,b:255,a:255},specularC:{r:255,g:255,b:255,a:255},transform:[[1,0,0,-2],[0,1,0,0],[0,0,1,0],[0,0,0,1]]}),d=new Sphere({baseC:{r:0,g:0,b:255,a:255},specularC:{r:255,g:255,b:255,a:255},transform:[[1,0,0,0],[0,1,0,-2],[0,0,1,0],[0,0,0,1]]}),f=new Plane({baseC:{r:100,g:100,b:100,a:255},diffuseFactor:.8,specularFactor:1E-4,reflectionFactor:1E-4,transform:[[1,0,0,0],[0,1,0,0],[0,0,1,-1],[0,0,0,1]]}),g=new OmniLight({intensity:1,source:{x:0,y:0,z:1,h:1}}),h=[];h.push(b);h.push(a);h.push(e);h.push(c);
h.push(d);h.push(f);h.push(g);var l=new Raytracer({world:h,pixelRenderer:window.canvas2D});console.log(l);setTimeout(function(){return l.render()},2E3);$(window).on("resize",function(){l.render()})})})();
